#!/usr/bin/env python3
"""Render and validate the credential-safe Codex host profile for 1102tools.

Codex plugin MCP declarations intentionally do not contain user credential
values.  Codex also does not merge a partial host declaration into a plugin
declaration with the same server name.  This profile therefore repeats the
complete launcher definition for the affected shared servers and allowlists
credential variable names with ``env_vars``.  Values remain in the launching
environment and are never written to the profile.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.9/3.10 lifecycle hosts
    tomllib = None  # type: ignore[assignment]


PROFILE_NAME = "1102tools-host"
SERVER_CONFIG = (
    (
        "sam-gov",
        "sam-gov-mcp==1.0.9",
        "sam-gov-mcp",
        "3",
        ("SAM_API_KEY",),
        (),
    ),
    (
        "usaspending",
        "usaspending-gov-mcp==1.0.4",
        "usaspending-mcp",
        "3",
        (),
        (("USASPENDING_TOOL_PROFILE", "acquisition-agent"),),
    ),
    (
        "bls-oews",
        "bls-oews-mcp==1.0.6",
        "bls-oews-mcp",
        "3",
        ("BLS_API_KEY",),
        (),
    ),
    (
        "regulations-gov",
        "regulationsgov-mcp==1.0.5",
        "regulationsgov-mcp",
        "4",
        ("REGULATIONS_GOV_API_KEY",),
        (),
    ),
    (
        "gsa-perdiem",
        "gsa-perdiem-mcp==1.0.6",
        "gsa-perdiem-mcp",
        "3",
        ("PERDIEM_API_KEY",),
        (),
    ),
)
KNOWN_CREDENTIALS = {
    "SAM_API_KEY",
    "BLS_API_KEY",
    "REGULATIONS_GOV_API_KEY",
    "PERDIEM_API_KEY",
}


def render_profile() -> str:
    lines = [
        "# Generated by tests/lifecycle/codex_host_profile.py.",
        "# Select with: codex --profile 1102tools-host",
        "# Credential values remain in the launching environment.",
        "",
    ]
    for name, package, executable, interval, env_vars, extra_env in SERVER_CONFIG:
        lines.extend(
            (
                f'[mcp_servers."{name}"]',
                'command = "uvx"',
                f'args = ["--from", "{package}", "{executable}"]',
            )
        )
        if env_vars:
            rendered = ", ".join(f'"{item}"' for item in env_vars)
            lines.append(f"env_vars = [{rendered}]")
        lines.extend(("", f'[mcp_servers."{name}".env]'))
        lines.append(f'FEDERAL_API_MIN_INTERVAL_SECONDS = "{interval}"')
        for key, value in extra_env:
            lines.append(f'{key} = "{value}"')
        lines.append("")
    return "\n".join(lines)


def validate_profile(text: str) -> list[str]:
    failures: list[str] = []
    if tomllib is None:
        for name, package, executable, interval, env_vars, extra_env in SERVER_CONFIG:
            required = (
                f'[mcp_servers."{name}"]',
                'command = "uvx"',
                f'args = ["--from", "{package}", "{executable}"]',
                f'[mcp_servers."{name}".env]',
                f'FEDERAL_API_MIN_INTERVAL_SECONDS = "{interval}"',
            )
            if any(item not in text for item in required):
                failures.append(f"{name}: complete server table is missing or stale")
            for credential in env_vars:
                if f'env_vars = ["{credential}"]' not in text:
                    failures.append(f"{name}: credential allowlist differs")
            for key, value in extra_env:
                if f'{key} = "{value}"' not in text:
                    failures.append(f"{name}: static environment differs")
        for credential in KNOWN_CREDENTIALS:
            if f'{credential} = "' in text:
                failures.append(f"{credential}: credential value must not be written")
        return failures
    try:
        parsed = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        return [f"invalid TOML: {exc}"]
    servers = parsed.get("mcp_servers")
    if not isinstance(servers, dict):
        return ["mcp_servers table is missing"]
    expected_names = {item[0] for item in SERVER_CONFIG}
    if set(servers) != expected_names:
        failures.append("server inventory differs from the maintained host overlay")
    for name, package, executable, interval, env_vars, extra_env in SERVER_CONFIG:
        server = servers.get(name)
        if not isinstance(server, dict):
            failures.append(f"{name}: complete server table is missing")
            continue
        if server.get("command") != "uvx":
            failures.append(f"{name}: command must be uvx")
        if server.get("args") != ["--from", package, executable]:
            failures.append(f"{name}: launcher args or package pin differ")
        if server.get("env_vars", []) != list(env_vars):
            failures.append(f"{name}: credential allowlist differs")
        env = server.get("env")
        expected_env = {"FEDERAL_API_MIN_INTERVAL_SECONDS": interval, **dict(extra_env)}
        if env != expected_env:
            failures.append(f"{name}: static environment differs")
    for credential in KNOWN_CREDENTIALS:
        if f'{credential} = "' in text:
            failures.append(f"{credential}: credential value must not be written")
    return failures


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--output", type=Path, required=True)
    result.add_argument("--check", action="store_true")
    return result


def main(argv: Sequence[str] | None = None) -> int:
    args = parser().parse_args(argv)
    expected = render_profile()
    if args.check:
        if not args.output.is_file():
            raise SystemExit(f"missing profile: {args.output}")
        actual = args.output.read_text(encoding="utf-8")
        failures = validate_profile(actual)
        if actual != expected:
            failures.append("profile bytes differ from the maintained template")
        if failures:
            raise SystemExit("; ".join(failures))
        print(f"Validated {args.output}")
        return 0
    failures = validate_profile(expected)
    if failures:
        raise SystemExit("; ".join(failures))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
